### ISSUE TITLE
React.forwardRef example

### ISSUE THREAD

**Issue by tu4mo** [kripod/react-polymorphic-types#2]
I'm trying to figure out the example for forwardRef'd component.

- HeadingProps isn't used
- There does not seem to be a type called React.ForwardedRef

**Comment by kripod** [comment]
Thanks for your feedback!

`HeadingProps` are exported as an example to follow conventions set by libraries. Each component’s corresponding prop types are made available alongside the component itself, e.g.:

```ts
import { Heading, HeadingProps } from "@/components/Heading";
```

`React.ForwardedRef` is [available](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d04316d5956c19db81e0f484cc79ad77f8fdb0a2/types/react/index.d.ts#L561) in a separate `@react/types` package (which is [marked as a peer dependency](https://github.com/kripod/react-polymorphic-types/blob/326e7677daa4fc7f62ad70a918629276ca196fdb/package.json#L38-L40)).

**Comment by tu4mo** [comment]
Oh, I had types for React 16 installed. Thanks!
